places = ['Mexico','Spain', 'Japan', 'Korea','Italy']

print('Original Order: ')
print(places)
print('Sorted List: ')
print(sorted(places))
print('Print again to ensure it is in the original order')
print(places)
print('Reverse:')
print(sorted(places,reverse=True))
print('Orignal Form: ')
print(places)
places.reverse()
print('Reversed list: ')
print(places)
print('Reverse again to be back in teh orignal list: ')
places.reverse()
print(places)

print('Alphabetical order: ')
places.sort()
print(places)
print('Reverse-alphabetical order: ')
places.sort(reverse=True)
print(places)